title: mat_pataki
description: Personal site, blog
baseurl: ""
url: https://mpataki.github.io

theme: cvless

# site settings
taglong: building for the joy of it
tagshort: code | make | jam

# author settings
author:
  name: Mat Pataki
  email: matpataki@gmail.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  #facebook: username
  github: mpataki
  #instagram: username
  linkedin: mat-pataki-000b76a
  #stackoverflow: 0000000/username
  #x: username

cv: false

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
